Vagrant.configure("2") do |config|

  config.vm.box = "techforwardacademy/rocky9"
  config.vm.box_url = "https://boxes.techforward.ai/metadata/rocky9.json"
  config.vm.box_version = "1.0.0"

  config.ssh.username = "techforward"
  config.ssh.insert_key = false

  config.vm.hostname = "tf-rocky9"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
    vb.gui = true
  end

end
