Vagrant.configure("2") do |config|

  config.vm.box = "techforwardacademy/windows2025"
  config.vm.box_url = "https://boxes.techforward.ai/metadata/windows2025.json"
  config.vm.box_version = "1.0.0"

  config.vm.guest = :windows
  config.vm.communicator = "winrm"

  config.winrm.username = "techforward"
  config.winrm.password = "Vagrant@Lab2026#Admin!"
  config.winrm.transport = :plaintext
  config.winrm.basic_auth_only = true

  config.vm.hostname = "TF-WIN2025"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 2
    vb.gui = true
  end

end
